### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by KINGamerx7KerrS** [Sneglium/Always-Greener#1]
Why isn't the mod showing on ContentDB?

**Comment by Sneglium** [comment]
I removed it because the mod isn't finished and contains a bunch of glaring bugs, and I don't have the time to work on anything Luanti related right now. I might eventually get around to reworking the mod and when I do I'll re-release it on CDB, but until then anyone who really wants to use the uni finished version can get it from this repo.
